name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Install packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install cmake gcc g++ ninja-build -qq
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Ubuntu
        path: |
          /usr/local/bin/ragephoto-extract
          /usr/local/lib/libragephoto.so
          /usr/local/lib/pkgconfig/ragephoto.pc
          /usr/local/include/RagePhoto/
