name: Ubuntu

on: push

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install cmake gcc g++ ninja-build -qq
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --prefix ${{github.workspace}}/install/usr/local
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Ubuntu
        path: |
          ${{github.workspace}}/install/
