name: Ubuntu CXX
on: push

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
    strategy:
      matrix:
        cxxstd:
          - 11
          - 17
    steps:
    - name: Cloning
      uses: actions/checkout@v5
    - name: Install packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install cmake gcc g++ ninja-build -qq
    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DRAGEPHOTO_CXX_STANDARD=${{matrix.cxxstd}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja
    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}
    - name: Install
      run: cmake --install "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --prefix "${{github.workspace}}/install/usr/local"
    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: Ubuntu C++${{matrix.cxxstd}}
        path: ${{github.workspace}}/install/
