name: Windows

on: push

jobs:
  Release:
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --prefix ${{github.workspace}}/install
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Windows MSVC
        path: |
          ${{github.workspace}}/install/
