name: Windows CXX
on: push

jobs:
  Release:
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
          - amd64_arm64
        cxxstd:
          - 11
          - 17
    steps:
    - name: Cloning
      uses: actions/checkout@v5
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{matrix.arch}}
    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DRAGEPHOTO_CXX_STANDARD=${{matrix.cxxstd}} -DRAGEPHOTO_UNICODE=wincvt -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja
    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}
    - name: Install
      run: cmake --install "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --prefix "${{github.workspace}}/install"
    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: Windows MSVC C++${{matrix.cxxstd}} ${{matrix.arch}}
        path: ${{github.workspace}}/install/
